version: '3.4'



services:
  quiz:
    image: ${DOCKER_REGISTRY-}quiz
    depends_on:
      - "QuizAPI"
    build:
      context: ./Quiz
      dockerfile: Dockerfile
    ports:
      - 80:80   


  QuizAPI:
    image: markus228/QuizAPI:latest
    build:
      context: .
      dockerfile: Quiz/Dockerfile
    ports: 
      - 8080:8080 